spring.application.name=examen
spring.datasource.url=jdbc:mysql://localhost:3306/Certificaciones
spring.datasource.username=root
spring.datasource.password=R@r@Vez020906
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
